dezull_help_category:
    pattern: /
    defaults: { _controller: DezullHelpBundle:HelpCategory:index }

dezull_help_category_create:
    pattern: /create
    defaults: { _controller: DezullHelpBundle:HelpCategory:create }
    requirements:
        _method: POST

dezull_help_category_edit:
    pattern: /{id}/edit
    defaults: { _controller: DezullHelpBundle:HelpCategory:edit }
    requirements:
        id: \d+

dezull_help_category_update:
    pattern: /{id}/update
    defaults: { _controller: DezullHelpBundle:HelpCategory:update }
    requirements:
        _method: POST
        id: \d+

dezull_help_category_delete:
    pattern: /{id}/delete
    defaults: { _controller: DezullHelpBundle:HelpCategory:delete }
    requirements:
        _method: POST
        id: \d+

dezull_help_category_update_sequences:
    pattern: /update-sequences
    defaults: { _controller: DezullHelpBundle:HelpCategory:updateSequences }
    requirements:
        _method: POST
