# Help Browser
dezull_help_browser_home:
    pattern: /help
    defaults: { _controller: DezullHelpBundle:Browser:index }

dezull_help_browser_topic:
    pattern: /help/!{title}
    defaults: { _controller: DezullHelpBundle:Browser:index }

# Admin
_dezull_help_admin:
    prefix: /admin/help
    resource: "@DezullHelpBundle/Resources/config/routing/admin.yml"
